---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  objectstorage.k8s.io/authors: "Kubernetes Authors"
  objectstorage.k8s.io/license: "Apache V2"
  objectstorage.k8s.io/support: "https://github.com/kubernetes-sigs/container-object-storage-api"
  api-approved.kubernetes.io: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1979-object-storage-support

resources:
  - client/config/crd/objectstorage.k8s.io_bucketaccesses.yaml
  - client/config/crd/objectstorage.k8s.io_bucketaccessclasses.yaml
  - client/config/crd/objectstorage.k8s.io_bucketclasses.yaml
  - client/config/crd/objectstorage.k8s.io_bucketclaims.yaml
  - client/config/crd/objectstorage.k8s.io_buckets.yaml
  - controller
