---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-role
  namespace: default
rules:
  - apiGroups: ["objectstorage.k8s.io"]
    resources: ["bucketclaims", "bucketaccesses", "bucketclaims/status", "bucketaccesses/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["objectstorage.k8s.io"]
    resources: ["buckets"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: ["objectstorage.k8s.io"]
    resources: ["bucketclasses","bucketaccessclasses"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "serviceaccounts"]
    verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: default
roleRef:
  kind: Role
  name: controller
  apiGroup: rbac.authorization.k8s.io
