[book]
title = "Container Object Storage Interface"
description = "This site documents how to develop and deploy a Container Object Storage Interface (COSI) driver on Kubernetes."
authors = ["The Kubernetes Authors"]
