---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: container-object-storage-interface-controller
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/managed-by: kustomize

resources:
- resources/sa.yaml
- resources/rbac.yaml
- resources/deployment.yaml
